dependencies:
#- _license=1.1=py27_0
- accelerate=1.12.0=np19py27_p0
- alabaster=0.7.3=py27_0
- argcomplete=0.8.9=py27_0
- astroid=1.3.4=py27_0
- babel=1.3=py27_0
- bcolz=0.9.0=np19py27_0
- beautiful-soup=4.3.2=py27_1
- binstar=0.11.0=py27_0
- bitarray=0.8.1=py27_1
- blaze-core=0.8.0=np19py27_0
- blz=0.6.2=np19py27_0
- boto=2.38.0=py27_0
- bottleneck=1.0.0=np19py27_0
- cdecimal=2.3=py27_1
- certifi=14.05.14=py27_0
- cffi=1.1.0=py27_0
- clyent=0.3.4=py27_0
- colorama=0.3.3=py27_0
- configobj=5.0.6=py27_0
- cryptography=0.9.1=py27_0
- cython=0.22.1=py27_0
- cytoolz=0.7.3=py27_0
- datashape=0.4.5=np19py27_0
- decorator=3.4.2=py27_0
- docutils=0.12=py27_1
- dynd-python=0.6.5=np19py27_0
- enum34=1.0.4=py27_0
- fastcache=1.0.2=py27_0
- flask=0.10.1=py27_1
- gevent=1.0.1=py27_0
- gevent-websocket=0.9.3=py27_0
- glueviz=0.5.3=np19py27_0
- greenlet=0.4.7=py27_0
- grin=1.2.1=py27_2
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=vc9_4
- idna=2.0=py27_0
- iopro=1.7.2=np19py27_p0
- itsdangerous=0.24=py27_0
- jdcal=1.0=py27_0
- jedi=0.8.1=py27_0
- jinja2=2.7.3=py27_2
- joblib=0.8.4=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.0.0=py27_0
- jupyter_core=4.0.6=py27_0
- launcher=1.0.0=1
- llvmlite=0.5.0=py27_0
- logilab-common=0.63.2=py27_0
- lxml=3.4.4=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_1
- menuinst=1.0.4=py27_0
- mistune=0.5.1=py27_1
- mkl=11.3.1=0
- mkl-rt=11.1=p0
- mkl-service=1.0.0=py27_p2
- mklfft=2.0=np19py27_p1
- mock=1.0.1=py27_0
- msvc_runtime=1.0.1=vc9_0
- multipledispatch=0.4.7=py27_0
- mysql-python=1.2.5=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.0=py27_0
- networkx=1.9.1=py27_0
- node-webkit=0.10.1=0
- nose=1.3.7=py27_0
- numba=0.19.1=np19py27_0
- numbapro=0.19.0=np19py27_p0
- numexpr=2.4.4=np110py27_0
- numpy=1.10.0=py27_0
- openpyxl=1.8.5=py27_0
- pandas=0.16.1=np19py27_0
- pandas-datareader=0.2.0=py27_0
- path.py=8.1.1=py27_0
- patsy=0.3.0=np19py27_0
- pep8=1.6.2=py27_0
- pickleshare=0.5=py27_0
- pillow=2.8.2=py27_0
- pip=8.1.1=py27_0
- ply=3.6=py27_0
- psutil=2.2.1=py27_0
- py=1.4.27=py27_0
- pyasn1=0.1.7=py27_0
- pycosat=0.6.1=py27_0
- pycparser=2.14=py27_0
- pycrypto=2.6.1=py27_3
- pyflakes=0.9.2=py27_0
- pygments=2.0.2=py27_0
- pylint=1.4.2=py27_0
- pyopenssl=0.15.1=py27_1
- pyparsing=2.0.3=py27_0
- pyqt=4.10.4=py27_1
- pyreadline=2.0=py27_0
- pytables=3.2.0=np19py27_0
- pytest=2.7.1=py27_0
- python=2.7.*
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pywin32=219=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_0
#- qtconsole=4.0.1=py27_0
- quandl=2.8.8=np19py27_0
- requests=2.9.1=py27_0
- rope=0.9.4=py27_1
- runipy=0.1.3=py27_0
#- scikit-image=0.11.3=np19py27_0
#- scikit-learn=0.17.1=np110py27_0
#- scipy=0.16.0=np110py27_0
- setuptools=20.3=py27_0
- simplegeneric=0.8.1=py27_0
- six=1.10.0=py27_0
#- snowballstemmer=1.2.0=py27_0
- sockjs-tornado=1.0.1=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
#- spyder=2.3.5.2=py27_0
#- spyder-app=2.3.5.2=py27_0
- sqlalchemy=1.0.12=py27_0
#- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np19py27_0
- sympy=0.7.6=py27_0
- toolz=0.7.2=py27_0
- tornado=4.2=py27_0
- traitlets=4.0.0=py27_0
- ujson=1.33=py27_0
- unicodecsv=0.9.4=py27_0
- wheel=0.29.0=py27_0
- xlrd=0.9.3=py27_0
- xlsxwriter=0.7.3=py27_0
- xlwings=0.3.5=py27_0
- xlwt=1.0.0=py27_0
- zlib=1.2.8=vc9_2
- pip:
  - amqp==1.4.8
  - anyjson==0.3.3
#  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.3.2
  - billiard==3.3.0.22
#  - blaze==0.8.0
#  - celery==3.1.20
  - colorlog==2.6.1
  - eventlet==0.17.4
  - fredapi==0.3.7
#  - gc-helpers (d:\users\mutisya\code\google_cloud_helpers)==0.1.0
  - gcloud==0.10.1
  - googleapis-common-protos==1.1.0
  - googleappenginecloudstorageclient==1.9.22.1
  - httplib2==0.9.2
  - ipython-genutils==0.1.0
  - jsonmerge==1.1.0
  - jupyter-client==4.0.0
  - jupyter-core==4.0.6
#  - logit-helpers (d:\users\mutisya\code\logit_helpers)==0.1.0
  - mechanize==0.2.5
  - oauth2client==2.0.0.post1
  - protobuf==3.0.0b2
  - psycopg2==2.6.1
  - pyasn1-modules==0.0.8
  - python-memcached==1.57
  - redis==2.10.5
  - redis-simple-cache==0.0.8
  - rsa==3.3
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.0
  - yappi==0.94
  - ystockquote==0.2.4
