name: root
dependencies:
- _license=1.1
- accelerate
- alabaster
- argcomplete
- astroid
- babel
- bcolz
- beautiful-soup
#- binstar
- bitarray
- blaze-core
- blz
- boto
- bottleneck
- cdecimal
- certifi
- cffi
- clyent
- colorama
- conda-build
- configobj
- cryptography
- cython
- cytoolz
- datashape
- decorator
- docutils
- dynd-python
- enum34
- fastcache
- flask
- gevent
- gevent-websocket
#- glueviz
- greenlet
- grin
- h5py
- hdf5
- idna
- iopro
- itsdangerous
- jdcal
- jedi
- jinja2
- joblib
- jsonschema
- jupyter_client
- jupyter_core
#- launcher
- llvmlite
- logilab-common
- lxml
- markupsafe
- matplotlib
#- menuinst=1.0.4
- mistune
- mkl
- mkl-rt
- mkl-service
- mklfft
- mock
#- msvc_runtime=1.0.1
- multipledispatch
- mysql-python
#- nbconvert=4.0.0
#- nbformat=4.0.0
- networkx
- node-webkit
- nose
- numba
- numbapro
- numexpr
- numpy
- openpyxl
- pandas
- pandas-datareader
- path.py
- patsy
- pep8
- pickleshare
- pillow
- pip
- ply
- psutil
- psycopg2
- py
- pyasn1
- pycosat
- pycparser
- pycrypto
- pyflakes
- pygments
- pylint
- pyopenssl
- pyparsing
- pyqt
#- pyreadline=2.0
- pytables
- pytest
- python=2.7*
- python-dateutil
- pytz
#- pywin32=219
- pyyaml
- pyzmq
#- qtconsole=4.0.1
- quandl
- requests
- rope
- runipy
#- scikit-image=0.11.3
#- scikit-learn=0.17.1
#- scipy=0.16.0
- semantic_version
- setuptools
- simplegeneric
- six
#- snowballstemmer=1.2.0
- sockjs-tornado
- sphinx
- sphinx_rtd_theme
#- spyder=2.3.5.2
#- spyder-app=2.3.5.2
- sqlalchemy
#- ssl_match_hostname=3.4.0.2
- statsmodels
- sympy
- toolz
- tornado
- traitlets
- ujson
- unicodecsv
- wheel
- xlrd
- xlsxwriter
#- xlwings=0.3.5
- xlwt
- zlib
- pip:
  - amqp
  - anyjson
  - billiard
  - colorlog
  - eventlet
  - fredapi
  - gcloud
  - googleapis-common-protos
  - googleappenginecloudstorageclient
  - httplib2
  - ipython-genutils
  - jsonmerg
#  - jupyter-client==4.0.0
#  - jupyter-core==4.0.6
  - mechanize
  - oauth2client
  - protobuf
  - psycopg2
  - pyasn1-modules
  - python-memcached
  - redis
  - redis-simple-cache
  - rsa
  - tables
  - yappi
  - ystockquote
